# ---------------------------------------------------------------------------
# replay.tcl -- emit a standalone "session" script that redraws exactly the
#               eyes the -no_gui measurement pass produced.
#
# Why a generated script rather than only a native session file:
#   in -no_gui mode there are no windows or panels, so whatever a native
#   session writer emits there may contain no layout.  A replay script is
#   self-contained, diffable, and reproduces the eyes identically when you
#   source it in the GUI -- and it can still call the native session writer
#   once it IS running in the GUI, where the layout exists.
# ---------------------------------------------------------------------------

proc eye::write_replay {path cfg fsdb results} {
    set tpl {#!/usr/bin/env wv
# =========================================================================
# AUTO-GENERATED by DM_AUTOMATION measure_eye.tcl -- do not edit by hand.
#   source fsdb : @FSDB@
#   generated   : @DATE@
#   config      : @CFGNAME@
# Open in the WaveView GUI to redraw the measured eyes, e.g.
#   wv -k @BASENAME@
# =========================================================================

set LIBDIR [file join [file dirname [file normalize [info script]]] @LIBREL@]
source [file join $LIBDIR eye_lib.tcl]

set FSDB      "@FSDB@"
set UI_VALUE  "@UI@"
set EYE_SHIFT "@PHASE@"
set VAC_VALUE "@VAC@"
set EYE_TYPE  "@TYPE@"

set fh [sx_open_sim_file_read $FSDB]

# Open the panel BEFORE creating any eye: sx_create_eye only builds the data
# object, and some builds attach a new eye to the current window at creation
# time.  Without this the script completes silently with an empty window.
eye::ensure_window "@CFGNAME@ @FSDBTAIL@"

@BYTES@

# Persist a native WaveView session too, now that windows/panels exist.
eye::save_session "@SESSION@"
}

    set bytes ""
    foreach b [dict get $cfg byte_order] {
        set bc      [dict get $cfg bytes $b]
        set prefix  [dict get $bc pad_prefix]
        set idx     [dict get $bc dqs_idx]
        set bits    [dict get $bc bits]
        set vref    [dict get $results $b vref]
        set strobe  [eye::strobe_signal_name $prefix \
                        [dict get $cfg pdqs] [dict get $cfg ndqs] $idx]

        append bytes "# ---- byte $b : vref = $vref ------------------------------------------\n"
        append bytes "set trig$b \[sx_signal \"$strobe\"\]\n"
        append bytes "set VREF$b  $vref\n"
        foreach bit $bits {
            set dsig [eye::data_signal_name $prefix $bit]
            set ps   [eye::fmt_ps [dict get $results $b per_bit $bit]]
            append bytes "set eye_$bit \[eye::create \"$dsig\" \$trig$b \$UI_VALUE \$EYE_SHIFT\]\n"
            append bytes "sx_measure_eye \$eye_$bit type=\$EYE_TYPE vref=\$VREF$b vac=\$VAC_VALUE\n"
            append bytes "eye::show \$eye_$bit \"$bit\"    ;# measured aperture: $ps ps\n"
        }
        append bytes "\n"
    }

    set stem [file rootname $path]
    set body [string map [list \
        @FSDB@     $fsdb \
        @DATE@     [clock format [clock seconds] -format "%Y-%m-%d %H:%M:%S"] \
        @CFGNAME@  [dict get $cfg name] \
        @FSDBTAIL@ [file tail $fsdb] \
        @BASENAME@ [file tail $path] \
        @LIBREL@   [dict get $cfg lib_relpath] \
        @UI@       [dict get $cfg ui] \
        @PHASE@    [dict get $cfg eye_shift] \
        @VAC@      [dict get $cfg vac] \
        @TYPE@     [dict get $cfg eye_type] \
        @SESSION@  ${stem}.session \
        @BYTES@    $bytes \
    ] $tpl]

    set f [open $path w]
    puts $f $body
    close $f
    eye::log "replay script written: $path"
}
